### ISSUE TITLE
Automated MD generation is not working properly with Bug and Feature links

### ISSUE THREAD

**Issue by wrejcodes** [USM-ACM-IEEE/acmWebsite-React#13]
# ACM Website

Before opening a new issue, please take a moment to review our [**community guidelines**](https://github.com/USM-ACM/acmWebsite/blob/master/.github/CONTRIBUTING.md) to make the contribution process easy and effective for everyone involved.

**Before opening a new issue, you may find an answer in already closed issues**:
https://github.com/USM-ACM/acmWebsite/issues?q=is%3Aissue+is%3Aclosed

## Issue Type

- [x] Bug (https://github.com/USM-ACM/acmWebsite/blob/master/.github/CONTRIBUTING.md#bugs)
- [ ] Feature (https://github.com/USM-ACM/acmWebsite/blob/master/.github/CONTRIBUTING.md#features)

## Description
We need to fix the automated mark down on the issue templates for the bug and feature links

## Steps to reproduce
Create an issue and you won't have nice looking links for bug and features

**Comment by tctcodes** [comment]
Hey pull request #15 resolved this issue closing.
