### ISSUE TITLE
Calendar Component

### ISSUE THREAD

**Issue by Quinn-Donnelly** [USM-ACM-IEEE/acmWebsite-React#16]
# ACM Website

## Issue Type

- [ ] Bug (https://github.com/USM-ACM/acmWebsite/blob/master/.github/CONTRIBUTING.md#bugs)
- [x] Feature (https://github.com/USM-ACM/acmWebsite/blob/master/.github/CONTRIBUTING.md#features)

## Description
Create a calendar for the website.
You should first create a mock-up of what the solution to this looks like. Model it in [Lucidchart](https://www.lucidchart.com)
Once you have a model or a design (either writing code yourself or using a package to do so)

## Extra Info
The current ACM calendar uses a google calendar. It would be beneficial to have what ever is built to consume this calendar and display it. iCal links or Google API would be a good approach.

**Comment by tctcodes** [comment]
Link to npm react-google-calendar https://github.com/crashspringfield/react-google-calendar

**Comment by tctcodes** [comment]
https://www.lucidchart.com/invitations/accept/be528636-0cc0-42e8-8cde-5832faef7ea0

@Quinn-Donnelly @Justinnunez1717 @wrejcodes Linked above is my awesome calendar proposal which will use react-google-calendar.

**Comment by Quinn-Donnelly** [comment]
Looks good as far as I can see. I am curious to see what the month calendar view looks like (thematically wise). Other that that looks good for me, good work Master of the Web :100:

**Comment by Jubstron** [comment]
👌👌👌👌👌

**Comment by wrejcodes** [comment]
Looks good to me 👍 Well done !!

**Comment by tctcodes** [comment]
This was approved during the last web-dev meeting.  You are now ready to begin implementation.  Good job me.  Self-high-five!

**Comment by tctcodes** [comment]
@timthom64 I haven't made much progress this week because I'm preparing for final exams and taking care of final assignments.
