### ISSUE TITLE
About Page

### ISSUE THREAD

**Issue by wrejcodes** [USM-ACM-IEEE/acmWebsite-React#17]
# ACM Website

## Issue Type

- [ ] [Bug](https://github.com/USM-ACM/acmWebsite/blob/master/.github/CONTRIBUTING.md#bugs)
- [x] [Feature](https://github.com/USM-ACM/acmWebsite/blob/master/.github/CONTRIBUTING.md#features)

## Description
We need to create the about page for the ACM Website! Initial ideas of things we should talk about on this page are who we are as a National Organization and what our local chapter does. Discussion about what the look/feel and items that should be incorporated in this page are encouraged.

**Comment by wrejcodes** [comment]
Make sure to use lucid chart for mockup/design and ask for a review of design before proceeding with code! :100:

**Comment by tctcodes** [comment]
Hi! What progress have y'all made on designing the layout in Lucidchart?

**Comment by tctcodes** [comment]
@ColbPeyton Hi, just checking in.  What kind of progress have you made?  Remember at this point we are not expecting code.  Just a mock up done in lucid chart.  If you need help with Lucidchart let me know and I can help you out. Also, you should check out the mockup that BCRevels posted for the exec page.  That is a good example.  Here's a link: https://www.lucidchart.com/invitations/accept/8bcf426c-de11-451b-a2e2-ce6804f7f6fa

**Comment by ColbPeyton** [comment]
@timthom64 Hello, sorry I haven't made much of any progress yet. I had some work/school stuff that I needed to take care of. I'm new to Lucidchart, Jordan gave me a quick tutorial of it last night but I'm still learning. I'll try to have a mockup by Thursday afternoon.

**Comment by tctcodes** [comment]
@ColbPeyton Awesome! Thank you very much for checking in.  I look forward to seeing what you come up with.

**Comment by ColbPeyton** [comment]
@timthom64 Just finished the mock up about page. Let me know what you think.

**Comment by tctcodes** [comment]
@ColbPeyton Awesome!  Please post a link to your mock-up here.  It creates a point of reference, and allows others easy access to find it.  Thank you!

**Comment by tctcodes** [comment]
@ColbPeyton @crazyknight14 This design was approved at the last web dev meeting.  You are ready to begin implementation.  Keep up the good work!

**Comment by tctcodes** [comment]
@ColbPeyton @crazyknight14 Update?

**Comment by crazyknight14** [comment]
I’ve made some changes on lucid chart if you wish to look. Let me know if anything is missing.

**Comment by tctcodes** [comment]
Looks good we can talk about it more at the meeting later.
