### ISSUE TITLE
Useful links component 

### ISSUE THREAD

**Issue by tctcodes** [USM-ACM-IEEE/acmWebsite-React#19]
# ACM Website

## Issue Type

- [ ] [Bug](https://github.com/USM-ACM/acmWebsite/blob/master/.github/CONTRIBUTING.md#bugs)
- [x] [Feature](https://github.com/USM-ACM/acmWebsite/blob/master/.github/CONTRIBUTING.md#features)

## Description
Tasks for this should include coming up with a list of potential useful links and investigate how you would want this component to work with the website.  Before writing any code be sure to design a wireframe to layout this component.  Afterwards post a link to your lucidchart document in the comments and request a review from timthom64.  Also, be sure to include a list of your proposed useful links.

**Comment by tctcodes** [comment]
@KennethMiller What's the status?  How's your mock up coming along?

**Comment by tctcodes** [comment]
@KennethMiller This design was approved during the webdev meeting last week on 4/13/18. Awesome job! You are ready to begin implementation.  Please post a link to your lucid chart design here.

**Comment by tctcodes** [comment]
@KennethMiller Update?

**Comment by KennethMiller** [comment]
Sorry about the lack of updates.  Been sick since last week and trying to
catch up on missed school work.  Might have updates thursday.

**Comment by tctcodes** [comment]
I hope you're feeling better. I also understand that final exams and assignments are coming up.  Thanks for checking in.
