### ISSUE TITLE
Exec Page

### ISSUE THREAD

**Issue by tctcodes** [USM-ACM-IEEE/acmWebsite-React#20]
# ACM Website

## Issue Type

- [ ] [Bug](https://github.com/USM-ACM/acmWebsite/blob/master/.github/CONTRIBUTING.md#bugs)
- [x] [Feature](https://github.com/USM-ACM/acmWebsite/blob/master/.github/CONTRIBUTING.md#features)

## Description
Design a component to display your dear leaders to the world.  Be sure to include any exec contact information.  Before writing any code, please create a layout on lucidchart then link your lucid chart document in the comments.  Then request a review from timthom64.

**Comment by tctcodes** [comment]
Hi! What progress have y'all made on designing the layout for the exec page in Lucid chart?

**Comment by BCRevels** [comment]
Proposed layout should be live on Lucidchart.

**Comment by tctcodes** [comment]
Awesome sauce!  I'll give it a look and get you some feedback.  Hopefully tonight, but definitely by Sunday morning.

**Comment by tctcodes** [comment]
Wow! Excellent job using lucidchart to put together the layout of the exec page.  Maybe we will use this as an example in the next web meeting for how to use lucidchart.  Good thinking of a way to handle positions that may be vacant.  I think this is a very strong layout.  Awesome job! :100:

**Comment by Quinn-Donnelly** [comment]
Great work on UI design. Doesn't get much better that that, very impressive.

Pasting a view only link here for future reference.
(Note if you have permission to edit then you can still use this link to go there and edit)
https://www.lucidchart.com/invitations/accept/8bcf426c-de11-451b-a2e2-ce6804f7f6fa

**Comment by wrejcodes** [comment]
Yeah this is a solid way of doing UI design. I agree with everything said above. I think we should tell the other people to look at this example for the other front end design mockups. Way to go @BCRevels!

**Comment by tctcodes** [comment]
@BCRevels @alea0120 This was approved during the last web-dev meeting.  You are good to go for implementation.  Keep up the good work!

**Comment by BCRevels** [comment]
Certainly, I will get the implementation underway soon!
