### ISSUE TITLE
List View Component

### ISSUE THREAD

**Issue by Quinn-Donnelly** [USM-ACM-IEEE/acmWebsite-React#5]
# ACM Website

## Issue Type

- [ ] Bug (https://github.com/USM-ACM/acmWebsite/blob/master/.github/CONTRIBUTING.md#bugs)
- [x] Feature (https://github.com/USM-ACM/acmWebsite/blob/master/.github/CONTRIBUTING.md#features)

## Description
Create a component called ListView. That will do the following. Given an array of elements via props. Make a horizontal list using each element in the array. 
![list](https://user-images.githubusercontent.com/8989563/33087324-d004c724-ceaf-11e7-8736-78058e4e7733.PNG)
 
Something similar to this. Note that this component will likely receive many updates and we will iterate on it each time we require a more robust list but for now we will get this version working.

**Comment by Basanta78** [comment]
I have worked on this issue..Can you give me permission to access the repo?..Thank you

**Comment by wrejcodes** [comment]
This issue will be closed as it will be handled when the navigation feature is implemented
