### ISSUE TITLE
Merge the updates to the boilerplate

### ISSUE THREAD

**Issue by Quinn-Donnelly** [USM-ACM-IEEE/acmWebsite-React#8]
# ACM Website

## Issue Type

- [ ] Bug (https://github.com/USM-ACM/acmWebsite/blob/master/.github/CONTRIBUTING.md#bugs)
- [x] Feature (https://github.com/USM-ACM/acmWebsite/blob/master/.github/CONTRIBUTING.md#features)

## Description

The boilerplate has implemented the new router for react and much more time for a migration before we get too deep.

**Comment by wrejcodes** [comment]
Merged via #9
